export const API = 'API';
export const SET_USER_INFO = 'SET_USER_INFO';
export const TOGGLE_LOADER = 'TOGGLE_LOADER';
export const RESET_USER_INFO = "RESET_USER_INFO"

export const SET_ALL_RESERVATIONS = 'SET_ALL_RESERVATIONS';
export const ADD_RESERVATION = 'ADD_RESERVATION';
export const REMOVE_RESERVATION = 'REMOVE_RESERVATION';
export const UPDATE_RESERVATION = 'UPDATE_RESERVATION';